
(function(){const t=document.getElementById('theme-toggle');const h=document.documentElement;const k='sowhat-admin-theme';const stored=localStorage.getItem(k);if(stored)h.setAttribute('data-theme',stored);function update(){const d=h.getAttribute('data-theme');t.textContent=d==='dark'?'☾':'☀';}t.addEventListener('click',function(){const next=h.getAttribute('data-theme')==='dark'?'light':'dark';h.setAttribute('data-theme',next);localStorage.setItem(k,next);update();});update();})();
const S={config:null,status:null,report:null,busy:false};
const E={banner:document.querySelector('#banner'),sessionCookie:document.querySelector('#session-cookie'),cookiePreview:document.querySelector('#cookie-preview'),baseUrl:document.querySelector('#base-url'),endpointPath:document.querySelector('#endpoint-path'),refererPath:document.querySelector('#referer-path'),vehiclePagePath:document.querySelector('#vehicle-page-path'),discoveryEndpointPath:document.querySelector('#discovery-endpoint-path'),vehicleRoleId:document.querySelector('#vehicle-role-id'),discoverUnits:document.querySelector('#discover-units'),unitsInput:document.querySelector('#units-input'),pollInterval:document.querySelector('#poll-interval'),lookbackMinutes:document.querySelector('#lookback-minutes'),requestInterval:document.querySelector('#request-interval'),retentionDays:document.querySelector('#retention-days'),minDuration:document.querySelector('#min-duration'),maxGap:document.querySelector('#max-gap'),archiveType:document.querySelector('#archive-type'),tempProfile:document.querySelector('#temp-profile'),tempProcessing:document.querySelector('#temp-processing'),autoStart:document.querySelector('#auto-start'),saveConfig:document.querySelector('#save-config'),clearCookie:document.querySelector('#clear-cookie'),pollNow:document.querySelector('#poll-now'),togglePolling:document.querySelector('#toggle-polling'),refreshDashboard:document.querySelector('#refresh-dashboard'),startDate:document.querySelector('#start-date'),endDate:document.querySelector('#end-date'),stats:document.querySelector('#stats'),runtimeSummary:document.querySelector('#runtime-summary'),liveAlertsBody:document.querySelector('#live-alerts-body'),compileBody:document.querySelector('#compile-table-body'),dailyBody:document.querySelector('#daily-table-body'),unitsBody:document.querySelector('#units-table-body'),alertsExport:document.querySelector('#export-alerts'),compileExport:document.querySelector('#export-compile')};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const dt=v=>!v?'-':new Intl.DateTimeFormat('en-GB',{year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v));
const mins=v=>v===null||v===undefined||v===''?'-':Number(v).toFixed(2);
const badge=t=>t==='temp1+temp2'?'<span class="badge critical">Critical</span>':'<span class="badge warning">Warning</span>';
function banner(msg,tone){if(!msg){E.banner.innerHTML='';E.banner.className='status-strip hidden';return;}E.banner.textContent=msg;E.banner.className=`status-strip ${tone||'info'}`;}
async function api(url,opt){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const p=await r.json().catch(()=>({ok:false,error:'Invalid server response.'}));if(!r.ok||p.ok===false)throw new Error(p.error||`HTTP ${r.status}`);return p;}
function unitsText(units){return(units||[]).map(u=>`${u.id}|${u.label}`).join('\n');}
function parseUnits(text){return String(text||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const parts=line.split('|');const id=(parts[0]||'').trim();const label=(parts[1]||parts[0]||'').trim();return id?{id,label:label||id}:null;}).filter(Boolean);}
function applyConfig(c){S.config=c;E.baseUrl.value=c.solofleetBaseUrl||'';E.endpointPath.value=c.endpointPath||'';E.refererPath.value=c.refererPath||'';E.vehiclePagePath.value=c.vehiclePagePath||'';E.discoveryEndpointPath.value=c.discoveryEndpointPath||'';E.vehicleRoleId.value=c.vehicleRoleId||'';E.unitsInput.value=unitsText(c.units);E.pollInterval.value=c.pollIntervalSeconds||60;E.lookbackMinutes.value=c.requestLookbackMinutes||30;E.requestInterval.value=c.requestIntervalSeconds||120;E.retentionDays.value=c.historyRetentionDays||7;E.minDuration.value=c.minDurationMinutes||5;E.maxGap.value=c.maxGapMinutes??'';E.archiveType.value=c.archiveType||'liveserver';E.tempProfile.value=c.tempProfile||'-1';E.tempProcessing.value=c.temperatureProcessing||'';E.autoStart.checked=!!c.autoStart;E.cookiePreview.textContent=c.hasSessionCookie?`Cookie tersimpan: ${c.sessionCookiePreview}`:'Belum ada session cookie yang tersimpan.';}
function setDefaultDates(){const now=new Date();const end=now.toISOString().slice(0,10);const start=new Date(now.getTime()-6*86400000).toISOString().slice(0,10);if(!E.startDate.value)E.startDate.value=start;if(!E.endDate.value)E.endDate.value=end;}
function renderStats(){const live=S.status?.liveAlerts||[];const units=S.status?.units||[];const rep=S.report||{alerts:[],compileByUnitDay:[]};const active=new Set(live.map(x=>x.vehicle)).size;const crit=live.filter(x=>x.type==='temp1+temp2').length;E.stats.innerHTML=`<article class="stat-card"><span class="stat-label">Monitored Units</span><strong>${units.length}</strong><span class="stat-meta">Unit ddl yang aktif di config</span></article><article class="stat-card"><span class="stat-label">Live Alerts</span><strong>${live.length}</strong><span class="stat-meta">${active} unit masih error sekarang</span></article><article class="stat-card"><span class="stat-label">Critical Live</span><strong>${crit}</strong><span class="stat-meta">Temp1 + Temp2 sama-sama 0</span></article><article class="stat-card"><span class="stat-label">Range Incidents</span><strong>${rep.alerts.length}</strong><span class="stat-meta">${rep.compileByUnitDay.length} row compile di range</span></article>`;}
function renderRuntime(){const rt=S.status?.runtime,c=S.status?.config;if(!rt||!c){E.runtimeSummary.innerHTML='<div class="empty-state">Dashboard belum punya data runtime.</div>';return;}E.togglePolling.textContent=rt.isPolling?'Stop auto polling':'Start auto polling';E.togglePolling.className=rt.isPolling?'button-secondary':'button-primary';const pollState=rt.isPolling?'AUTO POLLING ON':'AUTO POLLING OFF';const cookieState=c.hasSessionCookie?'Session cookie ready':'Session cookie kosong';E.runtimeSummary.innerHTML=`<article class="source-card"><span class="source-kicker">Runtime</span><h3>${pollState}</h3><p>${esc(rt.lastRunMessage||'Idle')}</p></article><article class="source-card"><span class="source-kicker">Last Poll</span><h3>${dt(rt.lastRunFinishedAt)}</h3><p>Durasi ${rt.lastRunDurationMs?`${(rt.lastRunDurationMs/1000).toFixed(1)} detik`:'-'}</p></article><article class="source-card"><span class="source-kicker">Next Poll</span><h3>${dt(rt.nextRunAt)}</h3><p>Interval ${c.pollIntervalSeconds} detik</p></article><article class="source-card"><span class="source-kicker">Session</span><h3>${cookieState}</h3><p>${c.sessionCookiePreview||'Paste cookie lalu save config.'}</p></article>`;}
function renderLiveAlerts(){const rows=S.status?.liveAlerts||[];if(!rows.length){E.liveAlertsBody.innerHTML='<tr><td colspan="9" class="table-empty">Belum ada live alert. Kalau ini baru start, klik Poll now dulu.</td></tr>';return;}E.liveAlertsBody.innerHTML=rows.map(i=>{let ctx=`${i.temp1Min??'-'} / ${i.temp2Min??'-'} to ${i.temp1Max??'-'} / ${i.temp2Max??'-'}`;if(i.type==='temp1')ctx=`Temp2 ${i.temp2Min??'-'} to ${i.temp2Max??'-'}`;else if(i.type==='temp2')ctx=`Temp1 ${i.temp1Min??'-'} to ${i.temp1Max??'-'}`;return `<tr><td>${badge(i.type)}</td><td>${esc(i.unitLabel||i.vehicle)}</td><td>${esc(i.vehicle)}</td><td>${esc(i.label)}</td><td>${dt(i.startTimestamp)}</td><td>${dt(i.endTimestamp)}</td><td>${mins(i.durationMinutes)}</td><td>${i.minSpeed??'-'} to ${i.maxSpeed??'-'}</td><td>${ctx}</td></tr>`;}).join('');}
function renderCompile(){const rows=S.report?.compileByUnitDay||[];if(!rows.length){E.compileBody.innerHTML='<tr><td colspan="8" class="table-empty">Belum ada compile row di date range ini.</td></tr>';return;}E.compileBody.innerHTML=rows.map(r=>`<tr><td>${r.day}</td><td>${esc(r.vehicle)}</td><td>${r.incidents}</td><td>${r.temp1Incidents}</td><td>${r.temp2Incidents}</td><td>${r.bothIncidents}</td><td>${mins(r.totalMinutes)}</td><td>${mins(r.longestMinutes)}</td></tr>`).join('');}
function renderDaily(){const rows=S.report?.dailyTotals||[];if(!rows.length){E.dailyBody.innerHTML='<tr><td colspan="5" class="table-empty">Belum ada daily totals di range ini.</td></tr>';return;}E.dailyBody.innerHTML=rows.map(r=>`<tr><td>${r.day}</td><td>${r.units}</td><td>${r.incidents}</td><td>${r.criticalIncidents}</td><td>${mins(r.totalMinutes)}</td></tr>`).join('');}
function renderUnits(){const rows=S.status?.units||[];if(!rows.length){E.unitsBody.innerHTML='<tr><td colspan="9" class="table-empty">Belum ada unit di config. Isi ddl unit dulu.</td></tr>';return;}E.unitsBody.innerHTML=rows.map(r=>`<tr><td>${esc(r.label)}</td><td>${esc(r.id)}</td><td>${esc(r.vehicle||'-')}</td><td>${dt(r.lastSuccessAt)}</td><td>${dt(r.lastRecordAt)}</td><td>${r.recordsCount}</td><td>${r.incidentsCount}</td><td>${r.currentAlertsCount}</td><td>${r.lastError?`<span class="text-critical">${esc(r.lastError)}</span>`:'<span class="text-ok">OK</span>'}</td></tr>`).join('');}
function csv(name,rows){if(!rows.length)return;const h=Object.keys(rows[0]);const body=[h.join(','),...rows.map(row=>h.map(k=>{const text=String(row[k]??'');return text.includes(',')||text.includes('"')||text.includes('\n')?`"${text.replace(/"/g,'""')}"`:text;}).join(','))].join('\n');const blob=new Blob([body],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
async function loadConfig(){applyConfig(await api('/api/config'));}
async function loadDashboard(){if(S.busy)return;S.busy=true;try{setDefaultDates();const q=new URLSearchParams({startDate:E.startDate.value,endDate:E.endDate.value});const [status,report]=await Promise.all([api('/api/status'),api(`/api/report?${q.toString()}`)]);S.status=status;S.report=report;if(!S.config)applyConfig(status.config);else{E.cookiePreview.textContent=status.config.hasSessionCookie?`Cookie tersimpan: ${status.config.sessionCookiePreview}`:'Belum ada session cookie yang tersimpan.';E.vehicleRoleId.value=status.config.vehicleRoleId||E.vehicleRoleId.value;E.unitsInput.value=unitsText(status.config.units||[]);}renderStats();renderRuntime();renderLiveAlerts();renderCompile();renderDaily();renderUnits();banner('', 'info');}catch(err){banner(err.message,'error');}finally{S.busy=false;}}
async function saveConfig(){const payload={solofleetBaseUrl:E.baseUrl.value.trim(),endpointPath:E.endpointPath.value.trim(),refererPath:E.refererPath.value.trim(),vehiclePagePath:E.vehiclePagePath.value.trim(),discoveryEndpointPath:E.discoveryEndpointPath.value.trim(),vehicleRoleId:E.vehicleRoleId.value.trim(),units:parseUnits(E.unitsInput.value),pollIntervalSeconds:Number(E.pollInterval.value||60),requestLookbackMinutes:Number(E.lookbackMinutes.value||30),requestIntervalSeconds:Number(E.requestInterval.value||120),historyRetentionDays:Number(E.retentionDays.value||7),minDurationMinutes:Number(E.minDuration.value||5),maxGapMinutes:E.maxGap.value===''?null:Number(E.maxGap.value),archiveType:E.archiveType.value.trim(),tempProfile:E.tempProfile.value.trim(),temperatureProcessing:E.tempProcessing.value.trim(),autoStart:E.autoStart.checked};if(E.sessionCookie.value.trim())payload.sessionCookie=E.sessionCookie.value.trim();const res=await api('/api/config',{method:'POST',body:JSON.stringify(payload)});E.sessionCookie.value='';applyConfig(res.config);banner('Config berhasil disimpan.','success');await loadDashboard();}
async function clearCookie(){await api('/api/config',{method:'POST',body:JSON.stringify({sessionCookie:''})});E.sessionCookie.value='';await loadConfig();await loadDashboard();banner('Session cookie sudah dihapus.','success');}
async function discoverUnits(){banner('Lagi tarik daftar unit dari Solofleet...','info');const res=await api('/api/discover/units',{method:'POST',body:JSON.stringify({})});applyConfig(res.config);banner(`Ketemu ${res.units.length} unit dari discovery.`,'success');await loadDashboard();}
async function runPollNow(){banner('Polling manual lagi jalan...','info');await api('/api/poll/run',{method:'POST',body:JSON.stringify({})});await loadDashboard();banner('Polling manual selesai.','success');}
async function togglePolling(){const on=!!S.status?.runtime?.isPolling;banner(`${on?'Stop':'Start'} auto polling...`,'info');await api(on?'/api/poll/stop':'/api/poll/start',{method:'POST',body:JSON.stringify({})});await loadDashboard();banner(`Auto polling ${on?'dimatikan':'dinyalakan'}.`,'success');}
E.saveConfig.addEventListener('click',()=>saveConfig().catch(err=>banner(err.message,'error')));E.discoverUnits.addEventListener('click',()=>discoverUnits().catch(err=>banner(err.message,'error')));E.clearCookie.addEventListener('click',()=>clearCookie().catch(err=>banner(err.message,'error')));E.pollNow.addEventListener('click',()=>runPollNow().catch(err=>banner(err.message,'error')));E.togglePolling.addEventListener('click',()=>togglePolling().catch(err=>banner(err.message,'error')));E.refreshDashboard.addEventListener('click',()=>loadDashboard().catch(err=>banner(err.message,'error')));E.startDate.addEventListener('change',()=>loadDashboard().catch(err=>banner(err.message,'error')));E.endDate.addEventListener('change',()=>loadDashboard().catch(err=>banner(err.message,'error')));
E.alertsExport.addEventListener('click',()=>csv('solofleet-live-alerts.csv',(S.status?.liveAlerts||[]).map(i=>({unit_label:i.unitLabel,vehicle:i.vehicle,type:i.label,start:new Date(i.startTimestamp).toISOString(),end:new Date(i.endTimestamp).toISOString(),duration_minutes:i.durationMinutes,min_speed:i.minSpeed,max_speed:i.maxSpeed,temp1_min:i.temp1Min,temp1_max:i.temp1Max,temp2_min:i.temp2Min,temp2_max:i.temp2Max}))));
E.compileExport.addEventListener('click',()=>csv('solofleet-compile-by-day.csv',S.report?.compileByUnitDay||[]));
(async function boot(){setDefaultDates();await loadConfig();await loadDashboard();window.setInterval(()=>loadDashboard().catch(err=>banner(err.message,'error')),15000);})().catch(err=>banner(err.message,'error'));
